version: '2'

services:

  solr:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pdnd-ckan-solr
    image: teamdigitale/pdnd-ckan-solr
    stdin_open: true
    tty: true
